SET TERM !! ;

ALTER TABLE HISTORIA
   ADD PENDIENTE FLOAT!!
COMMIT !!

CREATE PROCEDURE DAME_AJUSTE_ADMIN_GLOBAL24 (
    fechaadmin date,
    combustible integer)
returns (
    ajuste float)
as
begin
  SELECT SUM(VOLUMEN1 - VOLUMEN2) AS AJUSTE FROM CLAVES
  WHERE FECHAADMIN=:FECHAADMIN AND COMBUSTIBLE=:COMBUSTIBLE INTO :AJUSTE;
  suspend;
end!!
COMMIT !!

GRANT SELECT ON CLAVES TO PROCEDURE DAME_AJUSTE_ADMIN_GLOBAL24!!
COMMIT !!

GRANT EXECUTE ON PROCEDURE DAME_AJUSTE_ADMIN_GLOBAL24 TO SYSDBA!!
COMMIT !!

SET TERM ; !!

